# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b9ec25e609c5c220ae86b08c54a36f5be73d57c1304e9da96c8978a8cf395281529780b008ca8c5c8e7ed2583577c98f699718fe106a89668e38458ca397613

test:
  secret_key_base: 1b01e2f7022160ccfaea3ccd579a0d3643bd1e8490ea40f6b783c9a25c3018342d2259ad24baf744ee4db4b83d12967b9c77bab6a9ebd118c775f3f371f39e8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
